#!/bin/sh

# Use neovim for vim if present.

[ -x "$(command -v vis)" ] && alias vim="vis"

[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# doas not required for some system commands
for command in umount updatedb su cryptsetup reboot shutdown poweroff; do
	alias $command="doas $command"
done; unset command

se() {
	choice="$(find ~/.local/bin -mindepth 1 -printf '%P\n' | fzf)"
	[ -f "$HOME/.local/bin/$choice" ] && $EDITOR "$HOME/.local/bin/$choice"
}

# Verbosity and other things you almost always want
alias \
	cp="cp -vr" \
	mv="mv -v" \
	rm="rm -vr" \
	bc="bc -q" \
	rsync="rsync -vrPluh" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner" \
  fmount="doas mount -o gid=$(id -g),uid=$USER" \
  ff="fastfetch" \
  neofetch="fastfetch" \
  sc="sc-im" \
  lf="lfrun" \
  make="make -j5"


# Colorize commands when possible
	#ls="ls -hN --color=auto --group-directories-first" \
alias \
  ls="ls -F --color=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"

# Shorten commands
alias \
	ka="killall" \
	g="git" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	z="zathura" \
  ll="ls -l" \
  la="ls -la" \
	vpn="curl -s https://am.i.mullvad.net/json | jq -r '.ip, .country, .city'" \
	cal="khal calendar" \
  pdf="rsvg-convert --dpi-x=600 --dpi-y=600 --format=pdf" \
  fmake="make && doas make install && make clean"
