music_directory		"/home/percy/Music/"
playlist_directory	"/home/percy/.config/mpd/playlists"
db_file             "/home/percy/.config/mpd/database"
log_file						"/home/percy/.local/state/mpd/log"
pid_file						"/home/percy/.local/state/mpd/pid"
state_file					"/home/percy/.local/state/mpd/state"
sticker_file				"/home/percy/.local/state/mpd/sticker.sql"

auto_update "yes"
bind_to_address "localhost"
port "6600"
restore_paused "yes"
#max_output_buffer_size "16384"
replaygain "off"
volume_normalization "no"

audio_output {
				type						"pipewire"
				name						"PipeWire"
				format					"*:*:*"
}

audio_output {
				type	"fifo"
				name	"Visualizer feed"
				path	"/tmp/mpd.fifo"
				format	"44100:16:2"
}
