music_directory		"~/Music"
playlist_directory	"~/.config/mpd/playlists"
db_file             "~/.config/mpd/database"
log_file						"~/.local/state/mpd/log"
pid_file						"~/.local/state/mpd/pid"
state_file					"~/.local/state/mpd/state"
sticker_file				"~/.local/state/mpd/sticker.sql"

auto_update "yes"
bind_to_address "localhost"
restore_paused "yes"
#max_output_buffer_size "16384"
replaygain "off"
volume_normalization "no"

audio_output {
        type            "alsa"
        name            "Bit-Perfect"
        device					"hw:Pro,0"
        format					"*:*:*"
        mixer_type			"none"
        dop							"yes"
}

audio_output {
				type						"pipewire"
				name						"PipeWire (BT)"
				mixer_type			"software"
}

audio_output {
				type	"fifo"
				name	"Visualizer feed"
				path	"/tmp/mpd.fifo"
				format	"44100:16:2"
}
